meta:
  environment: (( param "please set meta environment" ))
  dns_root: (( param "please set meta dns_root" ))
  security_groups: (( param "please set meta security_groups" ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

jobs:
  - name: go_carbon_z1
    networks:
      - name: go_graphite1
  - name: carbon_c_relay_z1
    networks:
      - name: go_graphite1
  - name: go_carbonapi_z1
    networks:
      - name: go_graphite1

properties:
  carbon-c-relay:
    replication: 2
    backends:
      - host: (( grab 0.go_carbon_z1.go_graphite1." meta.environment "." meta.dns.dns_root ))
        port: 2003
      - host: (( grab 1.go_carbon_z1.go_graphite1." meta.environment "." meta.dns.dns_root ))
        port: 2003
  carbonzipper:
    backends:
    - host: (( concat "http://" jobs.go_carbon_z1.networks.go_graphite1.static_ips.0 ":8080" ))
    - host: (( concat "http://" jobs.go_carbon_z1.networks.go_graphite1.static_ips.1 ":8080" ))


compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: go_graphite1
    type: dynamic
    cloud_properties:
      security_groups: (( grab meta.security_groups ))
