meta:
  environment: go-graphite-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: carbon_c_relay_z1
    networks:
      - name: go_graphite1
        static_ips: (( static_ips(0) ))
  - name: go_carbon_z1
    networks:
      - name: go_graphite1
        static_ips: (( static_ips(1, 2) ))
  - name: go_carbonapi_z1
    networks:
      - name: go_graphite1
        static_ips: (( static_ips(3) ))

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: go_graphite1
  type: manual
  subnets:
  - name: random
    range: 10.0.2.0/28
    reserved:
      - 10.0.2.1
      - 10.0.2.10
      - 10.0.2.11
    static:
      - 10.0.2.2 - 10.0.2.9
